# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MsgaiChatSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MsgaiChatSample
  pod 'MsgaiChat', :git => 'https://github.com/msgai/msgaichat-sdk-ios.git'
end
